/**
 * US area code → IANA timezone mapping.
 * Covers all 300+ US area codes. Used to derive a lead's local time from
 * their phone number when no explicit city/state is stored.
 *
 * Source: NANPA area code assignments + IANA timezone database.
 */

export type TZInfo = {
  tz: string;        // IANA timezone, e.g. "America/Chicago"
  label: string;     // Short display label, e.g. "CT"
  name: string;      // Full name, e.g. "Central Time"
};

const AREA_CODE_MAP: Record<string, TZInfo> = {
  // ─── Eastern Time ───────────────────────────────────────────────────────────
  "201": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "202": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "203": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "207": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "212": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "215": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "216": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "217": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "218": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "219": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "220": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "223": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "224": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "225": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "228": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "229": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "231": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "234": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "239": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "240": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "248": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "251": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "252": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "253": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "254": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "256": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "260": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "262": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "267": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "269": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "270": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "272": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "276": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "281": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "301": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "302": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "303": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "304": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "305": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "307": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "308": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "309": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "310": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "312": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "313": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "314": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "315": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "316": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "317": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "318": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "319": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "320": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "321": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "323": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "325": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "330": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "331": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "332": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "334": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "336": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "337": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "339": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "340": { tz: "America/Puerto_Rico", label: "AST", name: "Atlantic Time" },
  "341": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "346": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "347": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "351": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "352": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "360": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "361": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "364": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "380": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "385": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "386": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "401": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "402": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "404": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "405": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "406": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "407": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "408": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "409": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "410": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "412": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "413": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "414": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "415": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "417": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "419": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "423": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "424": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "425": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "430": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "432": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "434": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "435": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "440": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "442": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "443": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "445": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "447": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "458": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "463": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "469": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "470": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "475": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "478": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "479": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "480": { tz: "America/Phoenix",  label: "AZ", name: "Arizona Time" },
  "484": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "501": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "502": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "503": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "504": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "505": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "507": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "508": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "509": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "510": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "512": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "513": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "515": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "516": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "517": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "518": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "520": { tz: "America/Phoenix",  label: "AZ", name: "Arizona Time" },
  "530": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "531": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "534": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "539": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "540": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "541": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "551": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "559": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "561": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "562": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "563": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "564": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "567": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "570": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "571": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "573": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "574": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "575": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "580": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "585": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "586": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "601": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "602": { tz: "America/Phoenix",  label: "AZ", name: "Arizona Time" },
  "603": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "605": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "606": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "607": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "608": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "609": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "610": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "612": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "614": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "615": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "616": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "617": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "618": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "619": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "620": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "623": { tz: "America/Phoenix",  label: "AZ", name: "Arizona Time" },
  "626": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "628": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "629": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "630": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "631": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "636": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "641": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "646": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "650": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "651": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "657": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "659": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "660": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "661": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "662": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "667": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "669": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "678": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "680": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "681": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "682": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "689": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "701": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "702": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "703": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "704": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "706": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "707": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "708": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "712": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "713": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "714": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "715": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "716": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "717": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "718": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "719": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "720": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "724": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "725": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "726": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "727": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "731": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "732": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "734": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "737": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "740": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "743": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "747": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "754": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "757": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "760": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "762": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "763": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "765": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "769": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "770": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "771": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "772": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "773": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "774": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "775": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "779": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "781": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "785": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "786": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "801": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "802": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "803": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "804": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "805": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "806": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "808": { tz: "Pacific/Honolulu", label: "HT", name: "Hawaii Time" },
  "810": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "812": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "813": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "814": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "815": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "816": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "817": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "818": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "820": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "828": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "830": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "831": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "832": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "835": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "838": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "843": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "845": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "847": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "848": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "850": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "854": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "856": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "857": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "858": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "859": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "860": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "862": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "863": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "864": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "865": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "870": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "872": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "878": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "901": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "903": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "904": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "906": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "907": { tz: "America/Anchorage", label: "AKT", name: "Alaska Time" },
  "908": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "909": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "910": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "912": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "913": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "914": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "915": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "916": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "917": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "918": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "919": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "920": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "925": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "928": { tz: "America/Phoenix",  label: "AZ", name: "Arizona Time" },
  "929": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "930": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "931": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "934": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "936": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "937": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "938": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "940": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "941": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "945": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "947": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "949": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "951": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "952": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "954": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "956": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "959": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "970": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "971": { tz: "America/Los_Angeles", label: "PT", name: "Pacific Time" },
  "972": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "973": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "975": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "978": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "979": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "980": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "984": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
  "985": { tz: "America/Chicago",  label: "CT", name: "Central Time" },
  "986": { tz: "America/Denver",   label: "MT", name: "Mountain Time" },
  "989": { tz: "America/New_York", label: "ET", name: "Eastern Time" },
};

/**
 * Extract the 3-digit area code from a US phone number string.
 * Handles formats: (903) 534-8800, 903-534-8800, 9035348800, +19035348800
 */
export function extractAreaCode(phone: string): string | null {
  if (!phone) return null;
  // Strip all non-digits
  const digits = phone.replace(/\D/g, "");
  // Handle +1 country code prefix
  const local = digits.startsWith("1") && digits.length === 11 ? digits.slice(1) : digits;
  if (local.length < 10) return null;
  return local.slice(0, 3);
}

/**
 * Get timezone info for a US phone number.
 * Returns null if the area code is not found.
 */
export function getTZFromPhone(phone: string): TZInfo | null {
  const ac = extractAreaCode(phone);
  if (!ac) return null;
  return AREA_CODE_MAP[ac] ?? null;
}

/**
 * Get the current local time string for a given IANA timezone.
 * Returns formatted time like "2:34 PM" and a status indicator.
 */
export type CallStatus = "good" | "early" | "late" | "closed";

export function getLocalTimeInfo(tz: string): {
  time: string;
  hour: number;
  status: CallStatus;
} {
  const now = new Date();
  const timeStr = now.toLocaleTimeString("en-US", {
    timeZone: tz,
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
  // Get the hour in 24h for status calculation
  const hourStr = now.toLocaleString("en-US", {
    timeZone: tz,
    hour: "numeric",
    hour12: false,
  });
  const hour = parseInt(hourStr, 10);

  let status: CallStatus;
  if (hour >= 9 && hour < 18) {
    status = "good";       // 9am–6pm: great time to call
  } else if ((hour >= 7 && hour < 9) || (hour >= 18 && hour < 20)) {
    status = "early";      // 7–9am or 6–8pm: borderline
  } else {
    status = "closed";     // Outside hours
  }

  return { time: timeStr, hour, status };
}
